config/routes.rb
Rails.application.routes.draw do
  root "home#top"
  get "about" => "home#about"
  get "admin" => "users#mg"

  resources :users do
    resource :password, only:[:edit, :update]
    collection do
      post :login
      get :login_form
      get :logout
    end
  end

  resources :posts

  resources :likes, only: [:update, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates :name, {presence: true, uniqueness: true, length: {maximum: 20}}
  validates :email, {presence: true, uniqueness: true, length: {maximum: 100}, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i}}
  validates :password,{presence: true, on: :create}


end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :authenticate_user, {only:[:edit, :update, :destroy, :edit_password, :update_password, :mg]}
  before_action :ensure_correct_user, {only:[:edit, :update, :destroy, :edit_password, :update_password]}
  before_action :forbid_login_user, {only:[:new, :create, :login_form, :login]}
  before_action :admin_user, {only:[:mg]}

  def index
    @users = User.all.order(created_at: :desc)
  end
  def show
    @user = User.find_by(id: params[:id])
    @posts = Post.where(user_id: @user.id)
    @likes = Like.where(user_id: @user.id)
  end
  def new
    @user = User.new
  end
  def create
    @user = User.new(
      name: params[:name],
      email: params[:email],
      password: params[:password],
      img_name: "default_user.jpg",
      admin: false,
      body_length: nil,
      giraffe_type: nil,
      place: "サバンナ")
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_index_url
    else
      render :new
    end
  end
  def edit
    @user = User.find_by(id: params[:id])
  end
  def update
    @user = User.find_by(id: params[:id])
    @user.name = params[:name]
    @user.email = params[:email]
    @user.place = params[:place]
    @user.body_length = params[:body_length]
    @user.giraffe_type = params[:giraffe_type]
    if params[:image]
      @user.img_name = "#{@user.id}.jpg"
      image = params[:image]
      File.binwrite("public/users_img/#{@user.img_name}", image.read)
    end
    if @user.save
      redirect_to user_index_url
    else
      render :edit
    end
  end
  def destroy
    @user = User.find_by(id: params[:id])
    @user.destroy
    redirect_to user_index_url
  end

  def edit_password
    @user = User.find_by(id: params[:id])
  end
  def update_password
    @user = User.find_by(id: params[:id])
    if @user.authenticate(params[:old_password])
      if params[:new_password] == params[:confirmation_password]
        @user.password = params[:new_password]
        @user.save
        flash[:notice] ="パスワードを保存しました"
        redirect_to user_index_url
      else
        @error_message ="新しいパスワード(確認用)が一致しません"
        render :edit_password
      end
    else
      @error_message ="パスワードが違います"
      render :edit_password
    end

  end
#管理者のみアクセス可
  def mg
    @users = User.all.order(created_at: :desc)
    @posts = Post.all.order(created_at: :desc)
    @likes = Like.all.order(created_at: :desc)
  end

  # ログイン関連
  def login_form
    @user = User.new
  end
  def login
    @user = User.find_by(email: params[:email])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to post_index_url
    else
      @error_message = "メールアドレスまはたパスワードが間違っています"
      @email = params[:email]
      @password = params[:password]
      render :login_form
    end
  end
  def logout
    session[:user_id] = nil
    render :login_form
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user, {only:[:edit, :update, :destroy, :edit_password, :update_password, :mg]}
  before_action :ensure_correct_user, {only:[:edit, :update, :destroy, :edit_password, :update_password]}
  before_action :forbid_login_user, {only:[:new, :create, :login_form, :login]}
  before_action :admin_user, {only:[:mg]}

  def index
    @users = User.all.order(created_at: :desc)
  end
  def show
    @user = User.find_by(id: params[:id])
    @posts = @user.posts.order(created_at: :desc)
    @likes = @user.likes.order(created_at: :desc)
  end
  def new
    @user = User.new
  end
  def create
    @user = User.new(
      name: params[:name],
      email: params[:email],
      password: params[:password],
      img_name: "default_user.jpg",
      admin: false,
      body_length: nil,
      giraffe_type: nil,
      place: "サバンナ")
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] ="ようこそ"
      redirect_to users_url
    else
      render :new
    end
  end
  def edit
    @user = User.find_by(id: params[:id])
  end
  def update
    @user = User.find_by(id: params[:id])
    @user.name = params[:name]
    @user.email = params[:email]
    @user.place = params[:place]
    @user.body_length = params[:body_length]
    @user.giraffe_type = params[:giraffe_type]
    if params[:image]
      @user.img_name = "#{@user.id}.jpg"
      image = params[:image]
      File.binwrite("public/users_img/#{@user.img_name}", image.read)
    end
    if @user.save
      flash[:notice] ="ユーザー情報を更新しました"
      redirect_to user_url(@user)
    else
      flash.now[:notice] = ""
      render :edit
    end
  end
  def destroy
    @user = User.find_by(id: params[:id])
    @user.destroy
    flash[:notice] ="退会しました"
    redirect_to root_url
  end

#管理者のみアクセス可
  def mg
    @users = User.all.order(created_at: :desc)
    @posts = Post.all.order(created_at: :desc)
    @likes = Like.all.order(created_at: :desc)
  end

# ログイン関連
  def login_form
    @user = User.new
  end
  def login
    @user = User.find_by(email: params[:email])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      flash[:notice] ="ログインしました"
      redirect_to posts_url
    else
      @error_message = "メールアドレスまはたパスワードが間違っています"
      @email = params[:email]
      @password = params[:password]
      render :login_form
    end
  end
  def logout
    session[:user_id] = nil
    flash.now[:notice] ="ログアウトしました"
    render :login_form
  end

end

app/helpers/user_helper.rb
module UserHelper
end

app/views/user/edit.html.erb
<div class="main-content">
  <h1>編集する</h1>
  <p>投稿を編集できます</p>

  <div class="user-new">
    <dib class="error-message">
      <% @user.errors.full_messages.each do |message| %>
      <%= message %>
      <% end %>
    </dib>
    <%= form_tag(user_path(@user.id), method: :patch, multipart: true) do %>
    <p>ユーザー名</p>
    <input name="name" value="<%= @user.name %>">
    <p>メールアドレス</p>
    <input name="email" type="email" value="<%= @user.email %>">
    <p>場所</p>
    <i class="fas fa-map-marker-alt"></i><input name="place" value="<%= @user.place %>">
    <p>種類</p>
    <select name="giraffe_type" value="<%= @user.giraffe_type %>">
      <option value="">--選択してください--</option>
      <option value="マサイキリン">マサイキリン</option>
      <option value="コルドファンキリン">コルドファンキリン</option>
      <option value="ヌビアキリン">ヌビアキリン</option>
      <option value="ナイジェリアキリン">ナイジェリアキリン</option>
      <option value="アミメキリン">アミメキリン</option>
      <option value="ケープキリン">ケープキリン</option>
      <option value="アンゴラキリン">アンゴラキリン</option>
    </select>
    <p>体長</p>
    <input name="body_length" value="<%= @user.body_length %>">m
    <p>プロフィール画像</p>
    <input type="file" name="image" value="<%= @user.img_name %>"><br>
    <input type="submit" value="保存">
    <% end %>
    <%= link_to("パスワードの変更", "/user/#{@current_user.id}/edit_password") %>
  </div>
</div>

app/views/user/edit_password.html.erb
<div class="main-content">
  <h1>パスワードの変更</h1>
  <p></p>

  <div class="user-new">
    <dib class="error-message">
      <% @user.errors.full_messages.each do |message| %>
      <%= message %>
      <% end %>
      <%= @error_message %>
    </dib>
    <%= form_tag("/user/#{@current_user.id}/update_password", method: :put) do %>
    <p>現在のパスワード</p>
    <input type="password" name="old_password" value="">
    <p>新しいパスワード</p>
    <input type="password" name="new_password" value="">
    <p>新しいパスワード(確認用)</p>
    <input type="password" name="confirmation_password" value="">
    <input type="submit" value="保存">
    <% end %>
  </div>
</div>

app/views/user/login_form.html.erb
<div class="main-content">
  <h1>ログイン</h1>

  <div class="user-new">
    <dib class="error-message">
      <%= @error_message %>
    </dib>
    <%= form_tag("/login", method: :post) do %>
      <p>メールアドレス</p>
      <input name="email" type="email" value="<%= @email %>">
      <p>パスワード</p>
      <input name="password" type="password" value="<%= @password %>">
      <br>
      <input type="submit" value="ログイン">
    <% end %>
    <br><p><%= link_to("新規登録はこちら", new_user_path) %></p>
  </div>
</div>

app/views/user/mg.html.erb
    <!-- t.text "content"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.integer "user_id"

  create_table "users", force: :cascade do |t|
    t.string "name"
    t.string "email"
    t.string "password"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.string "img_name"
     -->
  <h1>ユーザー一覧</h1>
  <p>ここはユーザー一覧です(管理画面想定)</p>

  <div class="user-index">
    <h2>user</h2>
    <table>
      <tr><th>id</th><th>admin</th><th>user-name</th><th>email</th><th>password</th><th>img_name</th></tr>
      <% @users.each do |user| %>
      <tr>
        <td>
          <%= user.id %>
        </td>
        <td>
          <%= user.admin %>
        </td>
        <td>
          <%= link_to(user.name, "/user/#{user.id}") %>
        </td>
        <td>
          <%= user.email %>
        </td>
        <td>
          <%= user.password_digest %>
        </td>
        <td>
          <%= user.img_name %>
        </td>
      </tr>
      <% end %>
    </table>
  </div>

  <div class="user-index">
    <h2>post</h2>
    <table>
      <tr><th>id</th><th>content</th><th>user_id</th><th>created_at</th><th>updated_at</th></tr>
      <% @posts.each do |post| %>
      <tr>
        <td>
          <%= post.id %>
        </td>
        <td>
          <%= link_to(post.content, post_path(post.id)) %>
        </td>
        <td>
          <%= post.user_id %>
        </td>
        <td>
          <%= post.created_at %>
        </td>
        <td>
          <%= post.updated_at %>
        </td>
      </tr>
      <% end %>
    </table>
  </div>

  <div class="user-index">
    <h2>like</h2>
    <table>
      <tr><th>id</th><th>post_id</th><th>user_id</th></tr>
      <% @likes.each do |like| %>
      <tr>
        <td>
          <%= like.id %>
        </td>
        <td>
          <%= like.post_id %>
        </td>
        <td>
          <%= like.user_id %>
        </td>
      </tr>
      <% end %>
    </table>
  </div>

app/views/user/new.html.erb
<div class="main-content">
  <h1>新規登録</h1>
  <p>aaa</p>

  <div class="user-new">
    <dib class="error-message">
      <% @user.errors.full_messages.each do |message| %>
      <%= message %>
      <% end %>
    </dib>
    <%= form_tag(user_index_path, method: :post) do %>
      <p>ユーザー名</p>
      <input name="name" value="<%= @user.name %>">
      <p>メールアドレス</p>
      <input name="email" type="email" value="<%= @user.email %>">
      <p>パスワード</p>
      <input name="password" type="password" value="<%= @user.password %>">
      <br>
      <input type="submit" value="登録">
    <% end %>
  </div>
</div>

app/views/user/show.html.erb
<div class="main-content">
  <h1><%= @user.name %>さんのプロフィール</h1>

  <div class="user-show">
    <img src=<%= "/users_img/#{@user.img_name}" %> alt="profile_img">
    <p>場所：<%= @user.place %></p>
    <p>種類：<%= @user.giraffe_type %></p>
    <p>体長：<%= @user.body_length %>m</p>
    <p><%= @user.created_at %>に始めました</p>
    <% if @user.id == @current_user.id || @current_user.admin? %>
    <%= link_to("編集", edit_user_path) %>
    <%= link_to("退会", @user , method: :delete) %>
    <% end %>
  </div>

  <h2><%= @user.name %>さんの投稿</h2>
  <% @posts.each do |post| %>
  <div class="usershow-content">
    <div class="usershow-img">
      <img src="<%= "/users_img/#{post.user.img_name}" %>" alt="">
    </div>
    <div class="usershow-text">
      <div class="usershow-user">
        <%= link_to(post.user.name, user_path(post.user_id)) %>
      </div>
      <div class="usershow-tweet">
        <%= link_to(post.content, post_path(post.id)) %>
      </div>
      <div class="usershow-date">
        <%= post.created_at %>
      </div>
    </div>
  </div>
  <% end %>

  <h2><%= @user.name %>さんのお気に入り</h2>
  <% @likes.each do |like| %>
  <% post = Post.find_by(id: like.post_id) %>
  <div class="usershow-content">
    <div class="usershow-img">
      <img src="<%= "/users_img/#{post.user.img_name}" %>" alt="">
    </div>
    <div class="usershow-text">
      <div class="usershow-user">
        <%= link_to(post.user.name, user_path(post.user_id)) %>
      </div>
      <div class="usershow-tweet">
        <%= link_to(post.content, post_path(post.id)) %>
      </div>
      <div class="usershow-date">
        <%= post.created_at %>
      </div>
    </div>
  </div>
  <% end %>

</div>