config/routes.rb
Rails.application.routes.draw do
  root "home#top"
  get "about" => "home#about"
  get "admin" => "users#mg"

  resources :users do
    resource :password, only:[:edit, :update]
    collection do
      post :login
      get :login_form
      get :logout
    end
  end

  resources :posts

  resources :likes, only: [:update, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  validates :content, {presence: true, length: {maximum: 140}}
  validates :user_id, {presence: true}

  belongs_to :user
  has_many :likes, dependent: :destroy


end

app/controllers/post_controller.rb
class PostController < ApplicationController
  before_action :authenticate_user, {only:[:new, :create, :edit, :update, :destroy]}
  before_action :ensure_correct_user, {only:[:edit, :update, :destroy]}

  def index
    @posts = Post.all.order(created_at: :desc)
  end
  def show
    @post = Post.find_by(id: params[:id])
    @user = User.find_by(id: @post.user_id)
  end
  def new
    @post = Post.new
  end
  def create
    @post = Post.new(
      content: params[:content],
      user_id: @current_user.id)
    if @post.save
      redirect_to post_index_url
    else
      render :new
    end
  end
  def edit
    @post = Post.find_by(id: params[:id])
  end
  def update
    @post = Post.find_by(id: params[:id])
    @post.content = params[:content]
    if @post.save
      redirect_to post_index_url
    else
      render :edit
    end
  end
  def destroy
    @post = Post.find_by(id: params[:id])
    @post.destroy
    redirect_to post_index_url
  end

  # ログイン権限処理（post用）
  def ensure_correct_user
    @post = Post.find_by(id: params[:id])
    if @current_user.id == @post.user_id || @current_user.admin?
      flash[:notice] =""
    else
      flash[:notice] ="権限がありません"
      redirect_to post_index_url
    end
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user, {only:[:new, :create, :edit, :update, :destroy]}
  before_action :ensure_correct_user, {only:[:edit, :update, :destroy]}

  def index
    @posts = Post.all.order(created_at: :desc)
  end
  def show
    @post = Post.find_by(id: params[:id])
    @user = @post.user
  end
  def new
    @post = Post.new
  end
  def create
    @post = Post.new(
      content: params[:content],
      user_id: @current_user.id)
    if @post.save
      flash[:notice] = "投稿しました"
      redirect_to posts_url
    else
      render :new
    end
  end
  def edit
    @post = Post.find_by(id: params[:id])
  end
  def update
    @post = Post.find_by(id: params[:id])
    @post.content = params[:content]
    if @post.save
      flash[:notice] = "投稿を編集しました"
      redirect_to posts_url
    else
      render :edit
    end
  end
  def destroy
    @post = Post.find_by(id: params[:id])
    @post.destroy
    flash[:notice] = "削除しました"
    redirect_to posts_url
  end

  # ログイン権限処理（post用）
  def ensure_correct_user
    @post = Post.find_by(id: params[:id])
    if @current_user.id == @post.user_id || @current_user.admin?
      flash[:notice] =""
    else
      flash[:notice] ="権限がありません"
      redirect_to posts_url
    end
  end

end

app/helpers/post_helper.rb
module PostHelper
end

app/views/posts/edit.html.erb
<div class="main-content">
  <h1>編集する</h1>
  <p>投稿を編集できます</p>

  <div class="post-new">
    <dib class="error-message">
      <% @post.errors.full_messages.each do |message| %>
      <%= message %>
      <% end %>
    </dib>
    <%= form_tag(post_path(@post.id), method: :patch) do %>
    <textarea name="content"><%= @post.content %></textarea><br>
    <input type="submit" value="保存">
    <% end %>
  </div>
</div>

app/views/posts/index.html.erb
<% provide(:title, "投稿一覧") %>
<div class="main-content">
  <h1>投稿一覧</h1>
  <p>ここは投稿一覧です</p>

  <%= link_to("新規投稿", new_post_path) %>

  <% @posts.each do |post| %>
  <div class="postindex-content">
    <div class="postindex-img">
      <img src="<%= "/users_img/#{post.user.img_name}" %>" alt="">
    </div>
    <div class="postindex-text">
      <div class="postindex-user">
        <%= link_to(post.user.name, user_path(post.user_id)) %>
      </div>
      <div class="postindex-tweet">
        <%= link_to(safe_join(post.content.split("\n"), tag(:br)), post_path(post.id)) %>
      </div>
      <div class="postindex-icon">
        <%= render partial: 'likes/like', locals: { post: post } %>
      </div>
      <div class="postindex-date">
        <%= post.created_at %>
      </div>
    </div>
  </div>
  <% end %>

</div>

app/views/posts/new.html.erb
<div class="main-content">
  <h1>投稿する</h1>
  <p>今の気持ちを投稿してみよう</p>

  <div class="post-new">
    <dib class="error-message">
      <% @post.errors.full_messages.each do |message| %>
      <%= message %>
      <% end %>
    </dib>
    <%= form_tag(posts_path, method: :post) do %>
    <textarea name="content"><%= @post.content %></textarea><br>
    <input type="submit" value="投稿">
    <% end %>
  </div>
</div>

app/views/posts/show.html.erb
<div class="main-content">
<p><%= link_to("←投稿一覧へ", posts_path) %></p>

  <div class="postshow-content">
    <div class="postshow-user">
      <div class="postshow-img">
        <img src=<%= "/users_img/#{@user.img_name}" %> alt="profile_img">
      </div>
      <div class="postshow-name">
        <p><%= link_to(@user.name, user_path(@user.id)) %></p>
      </div>
    </div>
    <div class="postshow-tweet">
      <p><%= safe_join(@post.content.split("\n"), tag(:br)) %></p>
    </div>
    <div class="postshow-icon">
      <% if @current_user %>
        <% if Like.find_by(user_id: @current_user.id, post_id: @post.id) %>
          <%= link_to(like_path(@post.id) , method: :delete) do %><i class="fas fa-star favorite"></i><% end %>
        <% else %>
          <%= link_to(like_path(@post.id), method: :put) do %><i class="fas fa-star nofavorite"></i><% end %>
        <% end %>
        <%= Like.where(post_id: @post.id).count %>
      <% end %>
    </div>
    <div class="postshow-date">
      <p><%= @post.created_at %></p>
    </div>
    <div class="postshow-edit">
      <% if @current_user %>
        <% if @post.user_id == @current_user.id || @current_user.admin? %>
          <%= link_to("編集", edit_post_path) %>
          <%= link_to("削除", @post , method: :delete) %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>